import comp from "C:/VS Code/blog/src/.vuepress/.temp/pages/demo/计算机网络/TCP/TCP的基本认识.html.vue"
const data = JSON.parse("{\"path\":\"/demo/%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BD%91%E7%BB%9C/TCP/TCP%E7%9A%84%E5%9F%BA%E6%9C%AC%E8%AE%A4%E8%AF%86.html\",\"title\":\"TCP的基本认识\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"TCP的基本认识\",\"date\":\"2023-11-24T00:00:00.000Z\",\"tags\":[\"计算机基础\",\"计算机网络\"],\"categories\":[\"计算机网络\"],\"gitInclude\":[],\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://flipped1001.cn/demo/%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BD%91%E7%BB%9C/TCP/TCP%E7%9A%84%E5%9F%BA%E6%9C%AC%E8%AE%A4%E8%AF%86.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"博客主页\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"TCP的基本认识\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Flipped\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"计算机基础\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"计算机网络\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-11-24T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"TCP的基本认识\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2023-11-24T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Flipped\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"TCP基本认识\",\"slug\":\"tcp基本认识\",\"link\":\"#tcp基本认识\",\"children\":[{\"level\":3,\"title\":\"TCP的头格式：\",\"slug\":\"tcp的头格式\",\"link\":\"#tcp的头格式\",\"children\":[]},{\"level\":3,\"title\":\"TCP工作在那一层：\",\"slug\":\"tcp工作在那一层\",\"link\":\"#tcp工作在那一层\",\"children\":[]},{\"level\":3,\"title\":\"什么是TCP协议：\",\"slug\":\"什么是tcp协议\",\"link\":\"#什么是tcp协议\",\"children\":[]},{\"level\":3,\"title\":\"什么是TCP连接:\",\"slug\":\"什么是tcp连接\",\"link\":\"#什么是tcp连接\",\"children\":[]},{\"level\":3,\"title\":\"如何确定一个TCP连接：\",\"slug\":\"如何确定一个tcp连接\",\"link\":\"#如何确定一个tcp连接\",\"children\":[]}]},{\"level\":2,\"title\":\"如何理解TCP是基于字节流的协议？\",\"slug\":\"如何理解tcp是基于字节流的协议\",\"link\":\"#如何理解tcp是基于字节流的协议\",\"children\":[]},{\"level\":2,\"title\":\"TCP半连接队列和全连接队列\",\"slug\":\"tcp半连接队列和全连接队列\",\"link\":\"#tcp半连接队列和全连接队列\",\"children\":[]},{\"level\":2,\"title\":\"SYN报文在什么情况下会被丢弃？\",\"slug\":\"syn报文在什么情况下会被丢弃\",\"link\":\"#syn报文在什么情况下会被丢弃\",\"children\":[]},{\"level\":2,\"title\":\"拔掉网线之后，TCP连接会消失吗？\",\"slug\":\"拔掉网线之后-tcp连接会消失吗\",\"link\":\"#拔掉网线之后-tcp连接会消失吗\",\"children\":[]},{\"level\":2,\"title\":\"为什么 tcp_tw_reuse 默认是关闭的？\",\"slug\":\"为什么-tcp-tw-reuse-默认是关闭的\",\"link\":\"#为什么-tcp-tw-reuse-默认是关闭的\",\"children\":[]},{\"level\":2,\"title\":\"用了TCP传输数据就一定不会丢包吗？\",\"slug\":\"用了tcp传输数据就一定不会丢包吗\",\"link\":\"#用了tcp传输数据就一定不会丢包吗\",\"children\":[]}],\"readingTime\":{\"minutes\":8.41,\"words\":2522},\"filePathRelative\":\"demo/计算机网络/TCP/TCP的基本认识.md\",\"localizedDate\":\"2023年11月24日\",\"excerpt\":\"\"}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
